// Package explain renders a derived value and its evidence for review.
package explain

import (
	"fmt"

	"github.com/example/routerctl/internal/regulatory/model"
)

func Constraint(manifest *model.DerivedManifest, key string) (string, error) {
	if manifest == nil || manifest.Kind != "DerivedManifest" {
		return "", fmt.Errorf("regulatory explain: unsupported derived manifest")
	}
	for _, constraint := range manifest.Constraints {
		if constraint.Key != key {
			continue
		}
		out := fmt.Sprintf("%s = %g %s\nRule: %s\nGenerated by: %s", constraint.Key, constraint.Value, constraint.Unit, constraint.Rule, constraint.GeneratedBy)
		for _, evidence := range constraint.Evidence {
			out += fmt.Sprintf("\nEvidence: %s page %d", evidence.Document, evidence.Page)
			if evidence.Table != "" {
				out += " (" + evidence.Table + ")"
			}
		}
		return out + "\n", nil
	}
	return "", fmt.Errorf("regulatory explain: constraint %q not found", key)
}
